LOG_DIR = ${DORIS_HOME}/log
JAVA_OPTS = "-Xms256m -Xmx1024m -XX:+UseG1GC"
JAVA_OPTS_FOR_JDK_17 = "-Dfile.encoding=UTF-8 -Djavax.security.auth.useSubjectCredsOnly=false -Xms256m -Xmx1024m -XX:+UseG1GC --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.xml/com.sun.org.apache.xerces.internal.jaxp=ALL-UNNAMED"
http_port = 8030
rpc_port = 9020
query_port = 9030
edit_log_port = 9010
meta_dir = ${DORIS_HOME}/doris-meta
